---
# Install Nginx, PHP5 (PHP-FPM), And Fcgiwrap
  
- name: Check if httpd Exists
  stat: path=/etc/init.d/httpd
  register: httpd_status
  
- name: Stop http 
  service: name=httpd state=stopped enabled=no
  when: httpd_status.stat.exists
  
- name: Install nginx
  yum: name=nginx state=present

- name: Copy new nginx configuration file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf backup=yes
  
- name: Activate nginx service 
  service: name=nginx state=started enabled=yes  

- name: install php-fpm 
  yum: name={{ item }} state=present
  with_items: ['php-fpm', 'php-cli', 'php-mysql', 'php-gd', 'php-pear', 'php-xml', 'php-pecl-apc', 'php-mbstring', 'php-mcrypt', 'php-soap']
  
#- name: Optional php modules 
#  yum: name={{ item }} state=present
#  with_items: ['php-imap', 'php-ldap', 'php-odbc', 'php-xmlrpc', 'php-magickwand', 'php-magpierss', 'php-mssql', 'php-shout', 'php-snmp', 'php-tidy']

- name: Comment out original error_reporting
  lineinfile: dest=/etc/php.ini regexp="^(error_reporting.*)" line=";\\1" backrefs=yes

- name: Configure error_reporting
  lineinfile: dest=/etc/php.ini insertafter="^;error_reporting = " line="error_reporting = E_ALL & ~E_NOTICE"

- name: Configure pathinfo
  lineinfile: dest=/etc/php.ini regexp="^cgi.fix_pathinfo=" line="cgi.fix_pathinfo=0"

- name: Configure timezone
  lineinfile: dest=/etc/php.ini regexp="^date.timezone = " line="date.timezone = \"Europe/Madrid\""

- name: activate php-fpm service
  service: name=php-fpm state=started enabled=yes

# Install phpMyAdmin

- name: Install phpMyAdmin
  yum: name=phpmyadmin state=present

- name: Configure access to phpmyadmin
  lineinfile: dest=/usr/share/phpmyadmin/config.inc.php regexp="^(\$cfg\['Servers'\]\[\$i\]\['auth_type'\])" line="\\1 = 'http';" backrefs=yes
