---
# Install PureFTPd

- name: Install PureFTPd
  yum: name={{ item }} state=present
  with_items:
    - pure-ftpd
    - openssl

- name: Enable TLS in PureFTPd
  lineinfile: dest=/etc/pure-ftpd/pure-ftpd.conf regexp="^# (TLS.*)" line="\\1" backrefs=yes
  
- name: Create certificate folder
  file: path=/etc/ssl/private state=directory
  
- name: Generate self-signed certificate
  command: openssl req -x509 -nodes -subj "/C=ES/ST=Barcelona/L=Barcelona/O=Ixole Activa SL/OU=Sistemas/CN=${ansible_fqdn}" -days 7300 -newkey rsa:2048 -keyout /etc/ssl/private/pure-ftpd.pem -out /etc/ssl/private/pure-ftpd.pem
  notify: restart pure-ftpd 
  
- name: Change certificate permissions
  file: path=/etc/ssl/private/pure-ftpd.pem mode=0600 
  
- name: Start PureFTPd 
  service: name=pure-ftpd state=started enabled=yes

# Install BIND

- name: Install BIND
  yum: name=bind state=present

- name: ensure ROOTDIR line is comment out
  lineinfile: dest=/etc/sysconfig/named regexp=^(ROOTDIR=.*) line="#\\1" backrefs=yes

- name: check if /etc/named.conf exists
  stat: path=/etc/named.conf
  register: named_conf

- name: Backup original named.conf file
  command: mv /etc/named.conf /etc/named.conf_bak
  when: named_conf.stat.exists

- name: Copy named.conf file
  copy: src=named.conf dest=/etc/named.conf 

- name: Create the file /etc/named.conf.local
  file: path=/etc/named.conf.local state=touch

- name: Disable BIND 
  service: name=named state=stopped enabled=no

# Install Webalizer And AWStats

- name: Install Webalizer And AWStats
  yum: name={{ item }} state=present
  with_items:
    - webalizer
    - awstats
    - perl-DateTime-Format-HTTP 
    - perl-DateTime-Format-Builder   

- name: Copy AWStats conf file
  copy: src=/etc/awstats/awstats.model.conf dest=/etc/awstats/awstats.conf

# Install Jailkit

- name: Check if jailkit is installed
  stat: path=/usr/sbin/jk_chrootsh
  register: jk_status

- name: Install Jailkit
  script: ../scripts/jailkit.sh
  when: jk_status.stat.exists == false

# Install ISPConfig 3

- name: Download ISPConfig 3
  command: wget http://www.ispconfig.org/downloads/ISPConfig-3-stable.tar.gz
  args: 
    chdir: /tmp
    